config/routes.rb
Rails.application.routes.draw do
  get('login', to: 'sessions#new')

  resource(:user)
  resolve('User') { [:user] }

  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  HighVoltage.configure do |config|
    config.home_page = 'home'
    config.route_drawer = HighVoltage::RouteDrawers::Root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence:   true,
                    uniqueness: { case_sensitive: false },
                    format:     { with: /\A[^@]+@[^@]+\z/ }
  has_secure_password

  before_save :format_email

  private

    def format_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html

html
  head
    title = yield(:page_title)
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      li = link_to 'Sign in', login_path
      li = link_to 'Sign up', new_user_path
    = yield

app/views/pages/home.html.slim
- content_for :page_title, 'The Bodega'

h1 The Bodega
p Order things from Toasteria's central kitchen.

app/views/users/new.html.slim
- content_for :page_title, 'Sign Up'

h1 Create an Account

= form_for :user do |f|
  p
    = f.label 'Name'
    = f.text_field 'name'

  p
    = f.label 'Email'
    = f.email_field 'email'

  p
    = f.label 'Password'
    = f.password_field 'password'

  p
    = f.label 'Confirm Password'
    = f.password_field 'password_confirmation'